name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm ci

    - name: Build userscript
      run: npm run build
      env:
        VERSION: ${{ env.VERSION }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/duofarmer.user.js
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: duofarmer-${{ env.VERSION }}
        path: dist/duofarmer.user.js
        retention-days: 30